### PR TITLE
Refactors changes related to demo configuration

### PR DESCRIPTION
**Pull request by DarshitChanpura**
There were recent changes to security demo configuration setup which now requires a custom admin Password to be setup. This PR updates the documentation and related code change.

### Check List
- [ ] Backport Labels added.   
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
@khushbr, @ansjcy, @sbcd90 can you folks take a look at this PR and merge it when possible (targeting 2.12.0 release)? It seems to me that the CI is not relying on admin:admin, the test failures look unrelated?

**Comment by DarshitChanpura** [comment]
@khushbr, @ansjcy, @sbcd90 nudge. Can you please add your reviews to this PR?

**Comment by DarshitChanpura** [comment]
@khushbr, @ansjcy, @sbcd90 This PR is still waiting to be merged and we are targetting 2.12 for this change. Can you please add your reviews to this PR?

**Review by ansjcy — APPROVED** [review]

**Review by atharvasharma61 — APPROVED** [review]

**Review by bbarani — APPROVED** [review]

**Comment by bbarani** [comment]
@khushbr @praveensameneni @sbcd90 Can you please check the errors on CI checks and merge the PR if they are expected?

**Pull request merged**
