### PR TITLE
Add auto backport functionality, backport delete, and documentation

### PR DESCRIPTION
**Pull request by dzane17**
Signed-off-by: David Zane <davizane@amazon.com>

### Description
Adds backport workflow to allow automatic backport PR creation as we merge to main or label PR. Explanation of script added to documentation.

#### Side Notes:
* We can label previously closed PRs and the action will run.
* As of right now we have to manually delete the branch that the bot creates. This could be changed in the future to be automatic.

### Issues Resolved
resolves https://github.com/opensearch-project/performance-analyzer-rca/issues/93

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dzane17** [comment]
Build fail may be expected, related to grpc-netty-shaded -> grpc-netty change [here](https://github.com/opensearch-project/performance-analyzer-rca/pull/129)

**Review by VachaShah — APPROVED** [review]
LGTM, thank you for adding this!

Just a small note: The description of the PR says we would have to manually delete the branch created by backport workflow. This is not applicable anymore since the `delete_backport_branch.yml` workflow added here does that. It will delete the source branches from backport PRs once the backport PRs are merged.

**Review by kkhatua — APPROVED** [review]

**Comment by dzane17** [comment]
> Just a small note: The description of the PR says we would have to manually delete the branch created by backport workflow. This is not applicable anymore since the `delete_backport_branch.yml` workflow added here does that. It will delete the source branches from backport PRs once the backport PRs are merged.

Ok, awesome. I removed that part.

**Comment by VachaShah** [comment]
You would also need to backport the auto delete workflow to your release branches where you are going to backport PRs. This way the auto delete can run on that particular branch when the backport PRs open. For example, when a backport PR is opened against `1.x`, auto delete can run on `1.x` so that the source branch is deleted after the backport PR is merged.

**Pull request merged**
