### PR TITLE
Deprecating Master nomenclature

### PR DESCRIPTION
**Pull request by kaushalmahi12**
**Is your feature request related to a problem? Please provide an existing Issue # , or describe.**
[Master Nomenclature Issue](https://github.com/opensearch-project/performance-analyzer-rca/issues/139)

**Describe the solution you are proposing**
This change is to stop the usage of `master` keyword in the performance-analyzer-rca codebase.

**Additional context**

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

This PR is broken down into multiple PRs
* [pr1](https://github.com/opensearch-project/performance-analyzer-rca/pull/206)
* [pr2](https://github.com/opensearch-project/performance-analyzer-rca/pull/208)
* [pr3](https://github.com/opensearch-project/performance-analyzer-rca/pull/209)
* [pr4](https://github.com/opensearch-project/performance-analyzer-rca/pull/210)
* [pr5](https://github.com/opensearch-project/performance-analyzer-rca/pull/211)
* [pr6](https://github.com/opensearch-project/performance-analyzer-rca/pull/212)

### CODE REVIEW

**Comment by kkhatua** [comment]
Review PR #206  
LGTM +1 
Ref: https://github.com/opensearch-project/performance-analyzer-rca/pull/206#pullrequestreview-1077919887

**Comment by kiranprakash154** [comment]
Approved [PR#212](https://github.com/opensearch-project/performance-analyzer-rca/pull/212) (pr6)

**Comment by kiranprakash154** [comment]
Approved [PR#208](https://github.com/opensearch-project/performance-analyzer-rca/pull/208#pullrequestreview-1078039842) (pr2) with **some nits**

**Comment by kkhatua** [comment]
@dzane17  reviewed & approved PR https://github.com/opensearch-project/performance-analyzer-rca/pull/209 (pr3)
@sruti1312   reviewed & approved PR https://github.com/opensearch-project/performance-analyzer-rca/pull/209 (pr4)
@sgup432  reviewed & approved PR https://github.com/opensearch-project/performance-analyzer-rca/pull/209 (pr5)

**Review by kkhatua — DISMISSED** [review]
Approved based on splintered predecessor PRs

**Review by kkhatua — DISMISSED** [review]

**Review by dzane17 — APPROVED** [review]

**Review by kkhatua — APPROVED** [review]

**Review by dzane17 — APPROVED** [review]

**Pull request merged**
